# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-28 07:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo_Card',
            fields=[
                ('Cargo_name', models.CharField(max_length=30, verbose_name='Cargo_name')),
                ('Quantity_s', models.IntegerField(max_length=50, verbose_name='Quantity_s')),
                ('Quantity_e', models.IntegerField(max_length=50, verbose_name='Quantity_b')),
                ('Loading_Port', models.CharField(max_length=60, verbose_name='Loading_Port')),
                ('Discharging_Port', models.CharField(max_length=30, verbose_name='Discharging_Port')),
                ('LayCan_S', models.DateField(default=datetime.date(1900, 1, 1), verbose_name='LayCan_S')),
                ('LayCan_E', models.DateField(default=datetime.date(1900, 1, 1), verbose_name='LayCan_E')),
                ('Sent', models.CharField(max_length=50, verbose_name='Sent')),
                ('ID', models.IntegerField(max_length=11, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_text', models.TextField(verbose_name='mail_text')),
            ],
            options={
                'db_table': 'cargo_card',
            },
        ),
        migrations.CreateModel(
            name='TC_Card',
            fields=[
                ('Account', models.CharField(max_length=30, verbose_name='Account')),
                ('Quantity_s', models.IntegerField(max_length=50, verbose_name='Quantity_s')),
                ('Quantity_e', models.IntegerField(max_length=50, verbose_name='Quantity_e')),
                ('Delivery_area', models.CharField(max_length=60, verbose_name='Delivery_area')),
                ('Redelivery_area', models.CharField(max_length=30, verbose_name='Redelivery_area')),
                ('LayCan_S', models.DateField(default=datetime.date(1900, 1, 1), verbose_name='LayCan_S')),
                ('LayCan_E', models.DateField(default=datetime.date(1900, 1, 1), verbose_name='LayCan_E')),
                ('DUR_S', models.IntegerField(max_length=50, verbose_name='DUR_S')),
                ('DUR_E', models.IntegerField(max_length=50, verbose_name='DUR_E')),
                ('Sent', models.CharField(max_length=50, verbose_name='Sent')),
                ('ID', models.IntegerField(max_length=11, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_text', models.TextField(verbose_name='mail_text')),
            ],
            options={
                'db_table': 'tc_card',
            },
        ),
        migrations.CreateModel(
            name='Tonnage_Card',
            fields=[
                ('Vessel_name', models.CharField(max_length=30, verbose_name='Vessel_name')),
                ('DWT', models.IntegerField(max_length=10, verbose_name='DWT')),
                ('BLT', models.IntegerField(max_length=60, verbose_name='BLT')),
                ('Open_area', models.CharField(max_length=30, verbose_name='Open_area')),
                ('Open_date_S', models.DateField(default=datetime.date(1900, 1, 1), max_length=50, verbose_name='Open_date_S')),
                ('Open_date_E', models.DateField(default=datetime.date(1900, 1, 1), max_length=50, verbose_name='Open_date_E')),
                ('Sent', models.CharField(max_length=50, verbose_name='Sent')),
                ('ID', models.IntegerField(max_length=11, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_text', models.TextField(verbose_name='mail_text')),
            ],
            options={
                'db_table': 'tonnage_card',
            },
        ),
    ]
