# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-17 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo_Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cargo_Name', models.CharField(max_length=30)),
                ('Quantity', models.CharField(max_length=50)),
                ('Loading_Port', models.CharField(max_length=60)),
                ('Discharging_Port', models.CharField(max_length=30)),
                ('LayCan', models.CharField(max_length=50)),
                ('Sent', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TC_Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account', models.CharField(max_length=30)),
                ('Quantity', models.CharField(max_length=50)),
                ('Delivery_Area', models.CharField(max_length=60)),
                ('Redelivery_Area', models.CharField(max_length=30)),
                ('LayCan', models.CharField(max_length=50)),
                ('DUR', models.CharField(max_length=50)),
                ('Sent', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tonnage_Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vessel_Name', models.CharField(max_length=30)),
                ('DWT', models.CharField(max_length=10)),
                ('BLT', models.IntegerField(max_length=60)),
                ('Open_Area', models.CharField(max_length=30)),
                ('Open_Date', models.CharField(max_length=50)),
                ('Sent', models.CharField(max_length=50)),
            ],
        ),
    ]
