# Generated by Django 2.1.7 on 2019-03-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo_Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cargo_Name', models.CharField(max_length=30, verbose_name='Cargo_Name')),
                ('Quantity', models.CharField(max_length=50, verbose_name='Quantity')),
                ('Loading_Port', models.CharField(max_length=60, verbose_name='Loading_Port')),
                ('Discharging_Port', models.CharField(max_length=30, verbose_name='Discharging_Port')),
                ('LayCan', models.CharField(max_length=50, verbose_name='LayCan')),
                ('Sent', models.CharField(max_length=50, verbose_name='Sent')),
            ],
        ),
        migrations.CreateModel(
            name='TC_Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account', models.CharField(max_length=30, verbose_name='Account')),
                ('Quantity', models.CharField(max_length=50, verbose_name='Quantity')),
                ('Delivery_Area', models.CharField(max_length=60, verbose_name='Delivery_Area')),
                ('Redelivery_Area', models.CharField(max_length=30, verbose_name='Redelivery_Area')),
                ('LayCan', models.CharField(max_length=50, verbose_name='LayCan')),
                ('DUR', models.CharField(max_length=50, verbose_name='DUR')),
                ('Sent', models.CharField(max_length=50, verbose_name='Sent')),
            ],
        ),
        migrations.DeleteModel(
            name='Cargo_Cards',
        ),
        migrations.DeleteModel(
            name='TC_Cards',
        ),
        migrations.AlterField(
            model_name='tonnage_cards',
            name='BLT',
            field=models.IntegerField(max_length=60, verbose_name='BLT'),
        ),
        migrations.AlterField(
            model_name='tonnage_cards',
            name='DWT',
            field=models.CharField(max_length=10, verbose_name='DWT'),
        ),
        migrations.AlterField(
            model_name='tonnage_cards',
            name='Open_Area',
            field=models.CharField(max_length=30, verbose_name='Open_Area'),
        ),
        migrations.AlterField(
            model_name='tonnage_cards',
            name='Open_Date',
            field=models.CharField(max_length=50, verbose_name='Open_Date'),
        ),
        migrations.AlterField(
            model_name='tonnage_cards',
            name='Sent',
            field=models.CharField(max_length=50, verbose_name='Sent'),
        ),
        migrations.AlterField(
            model_name='tonnage_cards',
            name='Vessel_Name',
            field=models.CharField(max_length=30, verbose_name='Vessel_Name'),
        ),
    ]
